#:import MDLabel kivymd.uix.label.MDLabel
#:import MDBoxLayout kivymd.uix.boxlayout.MDBoxLayout

<RegionalLeagueScreen>

    name: "RegionalLeagueScreen"

    MDBoxLayout:
        orientation: 'vertical'
        id: box1
        padding: 20
        spacing: 20
        size: root.width, root.height


        on_parent:
            for key, value in root.kupa.items():\
            box1.add_widget(MDBoxLayout(orientation="horizontal", md_bg_color=key, size_hint_x= 0.2, id=value))



